on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
name: stream-video

env:
    CARGO_TERM_COLOR: always

jobs:
    test-build-push:
        runs-on: ubuntu-latest
        steps:
            # checkout the repo
            - name: "Checkout GitHub Action"
              uses: actions/checkout@main
            - name: "Login via Azure CLI"
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: "Build and Push Image"
              uses: azure/docker-login@v1
              with:
                  login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
                  username: ${{ secrets.REGISTRY_USERNAME }}
                  password: ${{ secrets.REGISTRY_PASSWORD }}
            - run: |
                  export TAG=`date -u +"%Y%m%dT%H%M%SZ"`
                  docker buildx create --use
                  docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t tpark.azurecr.io/stream-video:1 --push .
